apiVersion: apps/v1
kind: Deployment
metadata:
  name: stress-pods
spec:
  replicas: 5
  selector:
    matchLabels:
      app: stress
  template:
    metadata:
      labels:
        app: stress
    spec:
      nodeSelector:
        role: worker   # only schedule on worker nodes
      containers:
      - name: stress
        image: alpine
        command: ["/bin/sh", "-c"]
        args:
          - "while true; do echo running; sleep 10; done"
