apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoscaler
spec:
  replicas: 3
  selector:
    matchLabels:
      app: autoscaler
  template:
    metadata:
      labels:
        app: autoscaler
    spec:
      serviceAccountName: autoscaler-sa   # <--- use dedicated service account
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: autoscaler
        image: local-autoscaler:latest
        imagePullPolicy: IfNotPresent
