# ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: autoscaler-sa
  namespace: default
---
# ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: autoscaler-role
rules:
  # Metrics API access
  - apiGroups: ["metrics.k8s.io"]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]

  # Core nodes access (needed to list nodes)
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]

  # Pods access (needed to list/delete pods)
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "delete"]
---
# ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: autoscaler-binding
subjects:
- kind: ServiceAccount
  name: autoscaler-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: autoscaler-role
  apiGroup: rbac.authorization.k8s.io
